# Generated by Django 4.1 on 2024-05-17 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0001_initial"),
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="member_check",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment",
                to="report.membercheck",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment",
                to=settings.AUTH_USER_MODEL,
                to_field="username",
            ),
        ),
    ]
