# Generated by Django 4.1 on 2024-02-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("student_id", models.CharField(max_length=50)),
                ("major", models.CharField(max_length=50, null=True)),
                ("attendance", models.IntegerField(default=0)),
                ("absent", models.IntegerField(default=0)),
                ("tardy", models.IntegerField(default=0)),
                ("etc", models.IntegerField(default=0)),
            ],
        ),
    ]
