# Generated by Django 4.1 on 2024-02-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("attendance", models.CharField(max_length=50)),
                ("date", models.CharField(max_length=50)),
            ],
        ),
    ]
