# Generated by Django 4.1 on 2024-02-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checking", "0004_member_grade"),
    ]

    operations = [
        migrations.CreateModel(
            name="GetImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="checking/post/%Y/%m/%d"),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="member",
            name="grade",
        ),
        migrations.DeleteModel(
            name="Grade",
        ),
    ]
