# Generated by Django 4.1 on 2024-02-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checking", "0005_getimage_remove_member_grade_delete_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="getimage",
            name="image",
            field=models.ImageField(blank=True, upload_to="checking/getimage/%Y/%m/%d"),
        ),
    ]
