# Generated by Django 4.1 on 2024-02-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checking", "0006_alter_getimage_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade_code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField()),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
