# Generated by Django 4.1 on 2024-02-20 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checking", "0008_member_grade_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="grade_code",
            new_name="grade",
        ),
    ]
