# Generated by Django 4.1 on 2024-02-20 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("checking", "0009_rename_grade_code_member_grade"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher_name", models.TextField()),
                ("grade_code", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.RemoveField(
            model_name="member",
            name="grade",
        ),
        migrations.DeleteModel(
            name="Grade",
        ),
        migrations.AddField(
            model_name="member",
            name="teacher",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="checking.teacher",
            ),
            preserve_default=False,
        ),
    ]
