# Generated by Django 4.1 on 2024-02-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checking", "0010_teacher_remove_member_grade_delete_grade_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="teacher",
        ),
        migrations.DeleteModel(
            name="Teacher",
        ),
    ]
