# Generated by Django 4.1 on 2024-02-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checking", "0012_teacher_member_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="teacher_name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
