# Generated by Django 4.1 on 2024-02-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checking", "0013_alter_teacher_teacher_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="grade_code",
            field=models.CharField(max_length=50),
        ),
    ]
