# Generated by Django 4.1 on 2024-02-20 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checking", "0014_alter_teacher_grade_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="student_id",
            new_name="grade_code",
        ),
        migrations.RemoveField(
            model_name="member",
            name="major",
        ),
        migrations.RemoveField(
            model_name="teacher",
            name="grade_code",
        ),
    ]
