# Generated by Django 4.1 on 2024-02-23 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("checking", "0015_rename_student_id_member_grade_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="teacher",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="checking.teacher",
            ),
            preserve_default=False,
        ),
    ]
