# Generated by Django 4.1 on 2024-02-23 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checking", "0016_attendance_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendance",
            name="teacher",
        ),
    ]
