# Generated by Django 4.1 on 2024-02-23 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("checking", "0017_remove_attendance_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="checking.teacher",
            ),
        ),
    ]
