# Generated by Django 4.1 on 2024-02-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checking", "0018_alter_member_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="teacher_name",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
