# Generated by Django 4.1 on 2024-03-01 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checking", "0019_attendance_teacher_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="etc",
        ),
        migrations.RemoveField(
            model_name="member",
            name="tardy",
        ),
    ]
