# Generated by Django 4.1 on 2024-03-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checking", "0022_remove_member_teacher_name_member_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="getimage",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
