# Generated by Django 4.1 on 2024-03-23 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checking", "0023_alter_getimage_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="grade_code",
        ),
        migrations.AddField(
            model_name="member",
            name="gender",
            field=models.CharField(default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="grade",
            field=models.CharField(default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="name",
            field=models.CharField(max_length=5),
        ),
    ]
