# Generated by Django 4.1 on 2024-03-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "checking",
            "0024_remove_member_grade_code_member_gender_member_grade_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="gender",
            field=models.CharField(default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="grade",
            field=models.CharField(default=None, max_length=3, null=True),
        ),
    ]
