# Generated by Django 4.1 on 2024-04-29 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checking", "0030_alter_member_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, verbose_name="이름")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "남성"), ("F", "여성")],
                        max_length=2,
                        verbose_name="성별",
                    ),
                ),
                ("birth", models.DateField(verbose_name="생년월일")),
                (
                    "phone_number",
                    models.CharField(
                        max_length=11,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$"
                            )
                        ],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=128, unique=True, verbose_name="이메일"
                    ),
                ),
                ("address", models.TextField(verbose_name="주소지")),
                ("register_at", models.DateField(verbose_name="신청 날짜")),
                ("funnels", models.TextField(verbose_name="접하게 된 경로")),
            ],
        ),
    ]
