# Generated by Django 4.1 on 2024-04-29 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checking", "0031_register"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="phone_number",
            field=models.CharField(
                max_length=13,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        regex="^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$"
                    )
                ],
            ),
        ),
    ]
