# Generated by Django 4.1 on 2024-04-30 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("checking", "0032_alter_register_phone_number"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Register",
        ),
        migrations.RenameField(
            model_name="member",
            old_name="absent",
            new_name="absent_count",
        ),
        migrations.RenameField(
            model_name="member",
            old_name="attendance",
            new_name="attendance_count",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="teacher",
        ),
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance",
                to="checking.member",
                to_field="name",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="name",
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
