# Generated by Django 4.1 on 2024-05-17 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("checking", "0033_delete_register_rename_absent_member_absent_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("worship", models.CharField(default=None, max_length=3, null=True)),
                ("meeting", models.CharField(default=None, max_length=3, null=True)),
                ("qt", models.CharField(default=None, max_length=3, null=True)),
                ("pray_time", models.CharField(default=None, max_length=4, null=True)),
                (
                    "pray_youth",
                    models.CharField(default=None, max_length=300, null=True),
                ),
                (
                    "pray_group",
                    models.CharField(default=None, max_length=300, null=True),
                ),
                (
                    "pray_user",
                    models.CharField(default=None, max_length=300, null=True),
                ),
                (
                    "pray_emergency",
                    models.CharField(default=None, max_length=300, null=True),
                ),
                ("date", models.DateTimeField()),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usercheck",
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MemberCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default=None, max_length=500, null=True)),
                (
                    "pray_member",
                    models.CharField(default=None, max_length=300, null=True),
                ),
                ("date", models.DateTimeField()),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membercheck",
                        to="checking.member",
                        to_field="name",
                    ),
                ),
            ],
        ),
    ]
