# Generated by Django 5.0.6 on 2024-06-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usercheck",
            name="pray_time",
        ),
        migrations.AddField(
            model_name="membercheck",
            name="gqs",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usercheck",
            name="issue",
            field=models.IntegerField(default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="usercheck",
            name="meeting",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="usercheck",
            name="qt",
            field=models.IntegerField(
                choices=[
                    (0, "0회"),
                    (1, "1회"),
                    (2, "2회"),
                    (3, "3회"),
                    (4, "4회"),
                    (5, "5회"),
                    (6, "6회"),
                    (7, "7회"),
                ],
                default=None,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="usercheck",
            name="worship",
            field=models.IntegerField(
                choices=[
                    (0, "불참"),
                    (1, "1부 예배"),
                    (2, "2부 예배"),
                    (3, "3부 예배"),
                ],
                default=None,
                max_length=3,
                null=True,
            ),
        ),
    ]
