# Generated by Django 5.0.6 on 2024-06-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0002_remove_usercheck_pray_time_membercheck_gqs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercheck",
            name="issue",
            field=models.CharField(default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="usercheck",
            name="qt",
            field=models.IntegerField(
                choices=[
                    (0, "0회"),
                    (1, "1회"),
                    (2, "2회"),
                    (3, "3회"),
                    (4, "4회"),
                    (5, "5회"),
                    (6, "6회"),
                    (7, "7회"),
                ],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="usercheck",
            name="worship",
            field=models.IntegerField(
                choices=[
                    (0, "불참"),
                    (1, "1부 예배"),
                    (2, "2부 예배"),
                    (3, "3부 예배"),
                ],
                default=None,
                null=True,
            ),
        ),
    ]
