# Generated by Django 5.0.6 on 2024-06-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0004_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercheck",
            name="title",
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
